# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ee73b85d94c1a8cfeb7261fdb69d6793d960fddcb94316403b527fe98ed4da29e06c170992106be30e8b23da91cf9d2cc19a5cca1ec749e4bdf5713dcd7f24f

test:
  secret_key_base: 565be9f8c1c408312b9bd090a512b4c710bd97d2cf2708e961ff77fb404a76c47463ec6927bb79c2a5a4a8d6873b6d5d9d3d79fb304ec29fa5d007a496b84cad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
